//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBProducts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Id_User { get; set; }
        public string Method { get; set; }
    }
}
