//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBProducts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public double Sale_Amount { get; set; }
        public string Id_Updated_By { get; set; }
        public System.DateTime Dt_Updated_By { get; set; }
    }
}
